const animationChallenge = {
  slug: 'animation-challenge',
  category: 'MOTION, 2D ANIMATION, 3D ANIMATION',
  title: '30-Day Animation Challenge',
  url: '',
  heroVideo: '/Animation challenge/header video.mp4',
  intro: [
    'During the Fall Semester of 2025, my friend and I challenged ourselves to a 30 Day Daily Animation Challenge.',
    '',
  ],
  meta: {
    role: 'Motion Design\n3D Animations',
    timeline: 'October 2025 - November 2025',
    team: 'Lailai Zhang',
    tools: 'Cinema 4D\nHoudini\nRedshift Render\nAfter Effects',
  },
  body: [
    { type: 'video', src: '/Animation challenge/1.mp4' },
    { type: 'label', text: 'DAY 1: PIXEL GAME ASSETS' },
    { type: 'video', src: '/Animation challenge/2.mp4' },
    { type: 'label', text: 'DAY 2: SNOW WITH HOUDINI VELLUM GRAIN' },
    { type: 'row', items: [{ src: '/Animation challenge/3 1.webp' }, { src: '/Animation challenge/3 2.webp' }] },
    { type: 'video', src: '/Animation challenge/4.mp4' },
    { type: 'label', text: 'DAY 3-8: RIVER BOAT SCENE' },
    { type: 'row', items: [{ src: '/Animation challenge/5 1.webp' }, { src: '/Animation challenge/5 2.webp' }] },
    { type: 'image', src: '/Animation challenge/6.webp' },
    { type: 'label', text: 'DAY 9 - 14: NEW FOREST SCENE' },
    { type: 'row', items: [{ src: '/Animation challenge/7 1.mp4' }, { src: '/Animation challenge/7 2.mp4' }] },
    { type: 'label', text: 'PARTICLE COLLISIONS, FLUID SIM', right: 'PARTICLE MESH FLIPBOOK' },
    { type: 'row', items: [{ src: '/Animation challenge/8 1.mp4' }, { src: '/Animation challenge/8 2.webp' }] },
    { type: 'label', text: 'LIGHTING, TEXTURE', right: 'FOG VOLUMES' },
    { type: 'image', src: '/Animation challenge/9.webp' },
    { type: 'label', text: 'FINAL STILL RENDER' },
    { type: 'video', src: '/Animation challenge/10.mp4' },
    { type: 'label', text: 'FINAL COMPOSITE' },
    {
      type: 'text',
      columns: [
        'Starting from day 17, I began looking into After Effects tutorials to achieve 2D effects that are limited by 3D softwares.',
        'I looked into Motion Graphics, 2D animations, and more abstracted elements, moving away from realistic river, trees, rocks to geometric shapes, color, and transitions.',
      ],
    },
    { type: 'row', items: [{ src: '/Animation challenge/11 1.mp4' }, { src: '/Animation challenge/11 2.mp4' }] },
    { type: 'label', text: 'DAY 17: MOTION BLUR', right: 'DAY 18: 3D LAYERS IN AFTER EFFECTS' },
    { type: 'video', src: '/Animation challenge/12.mp4' },
    { type: 'label', text: 'DAY 19: FOLLOW TRAIL' },
    {
      type: 'text',
      columns: [
        'Day 20 - 25, I worked on a longer Welcome Back Motion Graphic for our Design Big.',
        'Day 25 - 30, I worked on the Final 2D to 3D Animation inspired by Hyeonbin Kim (aflow) and Vladimir Marychev:',
      ],
    },
    { type: 'image', src: '/Animation challenge/13.webp' },
    { type: 'label', text: 'STORYBOARD' },
    { type: 'row', items: [{ src: '/Animation challenge/14 1.mp4' }, { src: '/Animation challenge/14 2.mp4' }] },
    { type: 'row', items: [{ src: '/Animation challenge/15 1.mp4' }, { src: '/Animation challenge/15 2.mp4' }] },
    { type: 'label', text: 'PROGRESS SNAPSHOTS' },
    { type: 'video', src: '/Animation challenge/16.mp4', sound: true },
    { type: 'label', text: 'FINAL COMPOSITE. PLEASE PLAY WITH SOUND.' },
  ],
};

export default animationChallenge;
