const rerender = {
  slug: 'rerender',
  category: 'INTERACTIVE WEB EXPERIENCE',
  title: 'Rerender',
  url: 'https://brendonlin-renderer.netlify.app/',
  heroImage: '/Rerender/rerender header crop.webp',
  heroNatural: true,
  intro: [
    'This project was inspired by something I noticed in my own work with motion graphics — a shift to more node-based, math-based, generated animation. I see this shift also happening in aesthetics and trends around me, moving into an ASCII aesthetic that almost describes our current age: fast developing AI tools and systems and a new relationship with information, code, and characters.',
    'Rendered is my playing and rebelling with that shift with re-introduced human participation.',
  ],
  meta: {
    role: 'Brand System Design\nInteraction Design\nWeb Developer',
    timeline: 'March - April 2026',
    team: 'Solo',
    tools: 'Figma\nProcessing\nTypescript, CSS, HTML',
  },
  body: [
    { type: 'image', src: '/Rerender/6.webp' },
    { type: 'label', text: 'BRAND AND COMPONENTS' },
    { type: 'image', src: '/Rerender/8.webp' },
    { type: 'image', src: '/Rerender/4.webp' },
     { type: 'image', src: '/Rerender/1.webp' },
    { type: 'video', src: '/Rerender/2.mp4' },
    { type: 'label', text: 'INTERACTIVE EXPERIENCE THROUGH DEVICE CAMERA AND MEDIAPIPE JS HANDS TRACKING' },
    { type: 'image', src: '/Rerender/3.webp' },
   
    { type: 'label', text: 'LANDING' },
    
    
    { type: 'image', src: '/Rerender/7.webp' },
    {
      type: 'text',
      columns: ['As a hidden easter egg, because this project was inspired by node-based motion graphics, the "Click Me" on the left bar reveals the name of the brand colors as generated by Cavalry, a node-based animation software.', 'Arctic: c4FDF6; Seagreen: 3EDB7D; Tomato: FF5B28; Plum: BEA5F6; Ivory: FDFDFD; Orchid: EC6CCD'],
    },
    
  ],
};

export default rerender;
